In [1]:
import sys
import numpy as np

print('Python: {}'.format(sys.version))
print('Numpy: {}'.format(np.__version__))

Python 3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ]
Numpy: 1.18.5


In [2]:
#defining a scalar

x = 4
x

4

In [3]:
#defining a vector

x = np.array((1,2,3))
x

array([1, 2, 3])

In [5]:
print('Vector Dimensions: {}'.format(x.shape))
print('Vector size: {}'.format(x.size))

Vector Dimensions: (3,)
Vector size: 3


In [6]:
#defining a matrix

x = np.matrix(([1,2,4],[4,5,6],[5,7,8]))
x

matrix([[1, 2, 4],
        [4, 5, 6],
        [5, 7, 8]])

In [7]:
print('Matrix Dimensions: {}'.format(x.shape))
print('Matrix size: {}'.format(x.size))

Matrix Dimensions: (3, 3)
Matrix size: 9


In [9]:
#defining a matrix of a given dimension

x = np.ones((10,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
print('Matrix Dimensions: {}'.format(x.shape))
print('Matrix size: {}'.format(x.size))

Matrix Dimensions: (10, 10)
Matrix size: 100


In [11]:
#tensors
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
print('Tensor Dimensions: {}'.format(x.shape))
print('Tensor size: {}'.format(x.size))

Tensor Dimensions: (3, 3, 3)
Tensor size: 27


In [13]:
#indexing
A = np.ones((5,5), dtype = np.int)
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
#indexing starts at 0

A[0,1] = 2
A

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
A[:1] = 3
A

array([[3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
A[:,:] = 8

In [17]:
A

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [18]:
# for higher dimensions, simply add an index

A = np.ones((5,5,5), dtype = np.int)

# assign first fow a new value
A[:,0,0] = 6
A

array([[[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [20]:
# matrix operations

A = np.matrix([[1,2],[3,4]])
B = np.ones((2,2), dtype = np.int)

In [21]:
# element wise sum
C = A + B
C

matrix([[2, 3],
        [4, 5]])

In [22]:
# element wise subtraction

C = A - B
C

matrix([[0, 1],
        [2, 3]])

In [23]:
# matrix multiplication

C = A*B
C

matrix([[3, 3],
        [7, 7]])

In [25]:
# matrix transpose

A = np.array(range(9))
A = A.reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
B = A.T
B

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [28]:
print(B.shape)
print(A.shape)

(3, 3)
(3, 3)


In [31]:
# tensors

A = np.ones((3,3,3,3,3,3,3,3,3))

In [32]:
print(A.shape)
print(len(A.shape))
print(A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3)
9
19683
